---
title: " Article1: World First Study Links Obesity With       Reduced Brain Plasticity"
description: "Analysis  the impact of obesity on brain plasticity"
author:
  - name: Ouane noubissi stephanie guilene
    url: {}
  - name: Nicolas Devilez
    url: {}
  - name: Engels Guyliann
    url: https://guyliann.netlify.com/fr
date: 10-24-2020
output: distill::distill_article
---

# I. Source Of The Article 

* Source:   [(https://www.sciencedaily.com/releases/2020/09/200924101936.htm)]
(september24, 2020)

* Word count:  384

# II. Vocabulary



| Word from the text                      | Synonym/ definition                                                                                                                    | French translation                    |
| --------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------- |
| Brain                                   | the mass of nerve tissue in the head of humans and animals that is the center of the nervous system                                    | Cerveau                               |
| Obesity                                 | Fatness                                                                                                                                | Obesité                               |
| Cardiovascular desease                  | disease that affects the heart and blood circulation                                                                                   | Maladie cardiovasculaire              |
| Health                                  | fitness                                                                                                                                | santé                                 |
| Pathway                                 | Passage                                                                                                                                | Voie, Chemin                          |
| Recovery                                | Recuperation, Healing                                                                                                                  | Recupération, Guérison                |
| Brain plasticity                        | Ability of the brain to modify its connections or re-wire itself perception                                                            | Plasticité cérébrale                  |
| Cognition                               | the mental act of learning; understanding; perception                                                                                  | Perception                            |
| Impair                                  | Make less effective; damage                                                                                                            |  Altérer; dégrader                    |
| Overweight                              | Person with excess body fat                                                                                                            | Surpoids; surcharge pondérale         |
| A raft of                               | A very large number of                                                                                                                 | Une série de; une panoplie de         |
| Dementia                                | Deterioration of mental faculties                                                                                                      | démence                               |
| Stroke                                  | Aploplexy                                                                                                                              | Accident vasculaire cérébral          |
| Burden                                  | Responsibility                                                                                                                         | Charge, Fardeau, Poids                |
| Brain injury                            | Damage to cerebral area                                                                                                                | Lésion cérébrale                      |
| Likely(that)                            | Probable                                                                                                                               | probable                              |
| Trans-cranial magnetic stimulation(TMS) | it's a noninvasive form of brain stimulation in which a changing magnetic fields is used to cause electric current at a specific area  | Stimulation magnétique transcrânienne |
|                                         | of the brain through electromagnetic induction                                                                                         |                                       |
| Strongly                                | Vigorously                                                                                                                             | Vigoureusement                        |


# III. Analysis Table About The Study


| Researchers       |       University of south Australia ( lead author: Dr Brenton Hordacre)                                                             |
| ----------------- | ------------------------------------------------------------------------------------------------ |
| Publish in? When? |  Science Daily (September 24,2020)                                                               |
| General topic     |    the impact of obesity on cerebral plasticity                                                  |
| Procedure         |   -tested 15 obese people aged between 18 and 60 comparing to 15 other people in a healthy       |
|                   |   weight control group using a series of experiments involving transcranial magnetic stimulation |
|                   | -repeat stimulation to see how strongly brain respond                                            |
| Conclusion        | - obesity was associated with impairs brain function                                             |
|                   | - these new finding suggest that losing weight is particularly important for healthy brain aged  |
|                   | - the ability of brain to find pathway is crucial to recovery                                    |

