---
title: "My English Activity Log : MEAL"
author:
  - name: "Ouane Noubissi Stephanie Guilene" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---


 - Oct. 30th: I have decided to change my devises language into English. Now my smartphone, computer, TV are all configured in English.

- jan. 28th: I have downloaded an application named "episode " on my phone. I have  started reading story about many thing to improve my vocabulary. the one i enjoyed  most was "the kiss list". it is about a girl who wanted to protect other from  bully in school since her elder sister try to suicide  after being bully by people in her school. problem was in image of  our society. i have read in the news many children who wanted to die due to bully in school or  in the social media.

- Fev. 1st: i have re-started to watch "the big bang theory" and my favorite amine "Naruto" in English with subtitles, it's really more funny than in French

- Fev 7th:  i have seen something about Henrietta Lacks, it was interesting i did not know who she was and i have make some research about her. i read a resume of "The Immortal Life of Henrietta Lacks" in internet(i didn't finish yet). I found it very interesting and sad but i have also learned many good thing.
she was an Afro-American woman who  died due to an invasive cancer.  Henrietta Lacks' cancer cells are found to have the unique characteristic of multiplying without limits when placed in the right conditions. their cells  helped scientists communities to develop  vaccine, to find how certain virus work for example they managed a vaccine against VPH  (it's a virus that infect woman's uterine), developed therapy against cancer(chemotherapy), improving fecundation "in vitro method". A lot of fantastic things that we are able to do now in the laboratory have started by analyzing these cells. it is amazing.

- Fev 18th: i've asked to my friend which english level is more than mine to helph me. we're trying to talk only in english.it's difficult i am always with my dictonnary to find the good word to express what i really want to say but i think it is also a good way for to understand words and master them.

- March 1st: i have started to select music i can listen in english. all of my favorite song are in english but all of them are not good to listen for improving my english. for example when i listened cardi B, she says many thing that it is not really grammatically exact in english so i'm trying to avoid it and just keep singer who sing really in  right english. my favourites singers remain adele, lauren daigle, ed sheeran, lewis capaldi

- March 29: coronavirus situation is still complicated and the vaccine developping by researchers is hazardous for certain people. i have read that most people have complications after using the vaccine  AstraZeneca such as pulmonary embolism but doctors said there's several other reason for it. hope that everything will be fine for them 

01/05/2021: covid situation is getting better now we're allow to go shopping or something else in the store without scheducle and soon we will allow to go out and see someone different than the wall of the house and teachers via teams or zoom.




