---
title: "CONCLUSION"
description: 
author:
  - name: ouane noubissi stephanie guilene
    url: {}
date: 04-11-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Working on my portfolio was  such of work and discovery for me. I had to read and analysed seven scientific articles. I had learned a lot of things about obesity and scientific research and it increased my motivation to be a researcher later.  I have learned that obesity is not only about a lack of willpower we have some factor in our body that can induce obesity and it not depend to our ability: it can be driven by a population of specific cells that impact our feeling and behaviour. Obesity can reduce brain plasticity and this capacity is much important for people to recovery after an accident for example.  Being obese increases your risk to develop others pathologies because some abnormal cells used fat as fuel to spread in the body like some cancers. Some factors which have linked with obesity could increase your vulnerability to others diseases like covid 19 because it increased the development of specific receptors which are dangerous for us due to their accumulation in our blood thus, they can spread into others systems and caused problems. I also learned that food security is important in household because babies in low food security tended to move into overweight and obesity rapidly. 



Word count : 206
